### PR TITLE
docs: fix syntax error in docstrings

### LINKED ISSUE #145: docs: syntax error in example from `plot_flows` docstring
https://github.com/scikit-mobility/scikit-mobility/blob/500e7e13769f6719f185930c563d9b20a62078f0/skmob/core/flowdataframe.py#L59

The following should work (I haven't run the tests):

```python
url_tess = skmob.utils.constants.NY_COUNTIES_2011
```

I can do a PR if needed.

### PR DESCRIPTION
**Pull request by pareyesv**
Fix error in the examples of the following docstrings: 

* `flowdataframe.py`
    * class `FlowDataFrame`
        * `get_flow`
        * `plot_flows`
        * `plot_tessellation`
* `radiation.py`
    * class `Radiation`
* `gravity.py`
    * class `Gravity` 

Close #145

### CODE REVIEW

**Comment by pareyesv** [comment]
@jonpappalord please let me know if you need any help.

**Comment by gbarlacchi** [comment]
Thanks! Could you please make a PR on the branch 1.2.x? We will include this change in the next release.

**Comment by pareyesv** [comment]
@gbarlacchi done!
See #155 (PR to branch 1.2.x)

Do you want to close this PR (to master)?

**Comment by gbarlacchi** [comment]
Add to another branch.

**Pull request closed without merging**
